name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened]       
jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node: [ 18, 20 ]

    steps:
    - uses: actions/checkout@v4

    # - name: Setup node | ${{ matrix.node}}
    - name: Setup node 
      uses: actions/setup-node@v4
      with:
        # node-version: ${{ matrix.node}}
        node-version: 18       
        cache: 'yarn'
    - run: yarn
    - run: yarn run test

    - name: Generate tag
      id: generate_tag
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4.3.1
      with:
        role-to-assume: arn:aws:iam::975050062685:role/ecr-role
        aws-region: us-east-2

    - name: Login to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

      
    # - name: Login into the container registry
    #   uses: docker/login-action@v3      
    #   with: 
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}

    # - name: Build and Push
    #   uses: docker/build-push-action@v6
    #   with:
    #     push: true
    #     tags: luc4sdev100/rocketseat-luc4sdev-ci-api:${{ steps.generate_tag.outputs.sha }},luc4sdev100/rocketseat-luc4sdev-ci-api:latest

    # - name: Build docker image
    #   run: docker build -t luc4sdev100/rocketseat-luc4sdev-ci-api:${{ steps.generate_tag.outputs.sha }} .

    # - name: Push image
    #   run: docker push luc4sdev100/rocketseat-luc4sdev-ci-api:${{ steps.generate_tag.outputs.sha }}